####################
####   CTS no OPT ##
###################
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
puts "===== THUC HIEN TREN GUI CUA ENCOUNTER ( SYNTHESIS CLOCK TREES)===="
